package cluster

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/lxc/lxd/lxd/db/query"
	"github.com/lxc/lxd/shared/api"
)

var _ = api.ServerEnvironment{}

var schemaObjects = RegisterStmt(`
SELECT schemas.id, schemas.version, schemas.updated_at
  FROM schemas
  ORDER BY schemas.version
`)

// GetSchemas returns all available schemas.
// generator: schema GetMany
func GetSchemas(ctx context.Context, tx *sql.Tx, filter SchemaFilter) ([]Schema, error) {
	var err error

	// Result slice.
	objects := make([]Schema, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	var args []any

	if filter.ID == nil && filter.Version == nil && filter.UpdatedAt == nil {
		sqlStmt = stmt(tx, schemaObjects)
		args = []any{}
	} else {
		return nil, fmt.Errorf("No statement exists for the given Filter")
	}

	// Dest function for scanning a row.
	dest := func(i int) []any {
		objects = append(objects, Schema{})
		return []any{
			&objects[i].ID,
			&objects[i].Version,
			&objects[i].UpdatedAt,
		}
	}

	// Select.
	err = query.SelectObjects(sqlStmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"schemas\" table: %w", err)
	}

	return objects, nil
}
