package cluster

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"

	"github.com/lxc/lxd/lxd/db/query"
	"github.com/lxc/lxd/shared/api"
)

var _ = api.ServerEnvironment{}

var secretObjects = RegisterStmt(`
SELECT secrets.id, secrets.token, secrets.joiner_cert
  FROM secrets
  ORDER BY secrets.joiner_cert
`)

var secretObjectsByJoinerCert = RegisterStmt(`
SELECT secrets.id, secrets.token, secrets.joiner_cert
  FROM secrets
  WHERE secrets.joiner_cert = ? ORDER BY secrets.joiner_cert
`)

var secretID = RegisterStmt(`
SELECT secrets.id FROM secrets
  WHERE secrets.joiner_cert = ?
`)

var secretCreate = RegisterStmt(`
INSERT INTO secrets (token, joiner_cert)
  VALUES (?, ?)
`)

var secretDeleteByJoinerCert = RegisterStmt(`
DELETE FROM secrets WHERE joiner_cert = ?
`)

// GetSecretID return the ID of the secret with the given key.
// generator: secret ID
func GetSecretID(ctx context.Context, tx *sql.Tx, joinerCert string) (int64, error) {
	stmt := stmt(tx, secretID)
	rows, err := stmt.Query(joinerCert)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"secrets\" ID: %w", err)
	}

	defer rows.Close()

	// Ensure we read one and only one row.
	if !rows.Next() {
		return -1, api.StatusErrorf(http.StatusNotFound, "Secret not found")
	}
	var id int64
	err = rows.Scan(&id)
	if err != nil {
		return -1, fmt.Errorf("Failed to scan ID: %w", err)
	}

	if rows.Next() {
		return -1, fmt.Errorf("More than one row returned")
	}
	err = rows.Err()
	if err != nil {
		return -1, fmt.Errorf("Result set failure: %w", err)
	}

	return id, nil
}

// SecretExists checks if a secret with the given key exists.
// generator: secret Exists
func SecretExists(ctx context.Context, tx *sql.Tx, joinerCert string) (bool, error) {
	_, err := GetSecretID(ctx, tx, joinerCert)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// GetSecret returns the secret with the given key.
// generator: secret GetOne
func GetSecret(ctx context.Context, tx *sql.Tx, joinerCert string) (*Secret, error) {
	filter := SecretFilter{}
	filter.JoinerCert = &joinerCert

	objects, err := GetSecrets(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"secrets\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "Secret not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"secrets\" entry matches")
	}
}

// GetSecrets returns all available secrets.
// generator: secret GetMany
func GetSecrets(ctx context.Context, tx *sql.Tx, filter SecretFilter) ([]Secret, error) {
	var err error

	// Result slice.
	objects := make([]Secret, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	var args []any

	if filter.JoinerCert != nil && filter.ID == nil && filter.Token == nil {
		sqlStmt = stmt(tx, secretObjectsByJoinerCert)
		args = []any{
			filter.JoinerCert,
		}
	} else if filter.ID == nil && filter.Token == nil && filter.JoinerCert == nil {
		sqlStmt = stmt(tx, secretObjects)
		args = []any{}
	} else {
		return nil, fmt.Errorf("No statement exists for the given Filter")
	}

	// Dest function for scanning a row.
	dest := func(i int) []any {
		objects = append(objects, Secret{})
		return []any{
			&objects[i].ID,
			&objects[i].Token,
			&objects[i].JoinerCert,
		}
	}

	// Select.
	err = query.SelectObjects(sqlStmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"secrets\" table: %w", err)
	}

	return objects, nil
}

// CreateSecret adds a new secret to the database.
// generator: secret Create
func CreateSecret(ctx context.Context, tx *sql.Tx, object Secret) (int64, error) {
	// Check if a secret with the same key exists.
	exists, err := SecretExists(ctx, tx, object.JoinerCert)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"secrets\" entry already exists")
	}

	args := make([]any, 2)

	// Populate the statement arguments.
	args[0] = object.Token
	args[1] = object.JoinerCert

	// Prepared statement to use.
	stmt := stmt(tx, secretCreate)

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"secrets\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"secrets\" entry ID: %w", err)
	}

	return id, nil
}

// DeleteSecret deletes the secret matching the given key parameters.
// generator: secret DeleteOne-by-JoinerCert
func DeleteSecret(ctx context.Context, tx *sql.Tx, joinerCert string) error {
	stmt := stmt(tx, secretDeleteByJoinerCert)
	result, err := stmt.Exec(joinerCert)
	if err != nil {
		return fmt.Errorf("Delete \"secrets\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "Secret not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d Secret rows instead of 1", n)
	}

	return nil
}
